### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by comword** [Silentlys/android_device_zte_N939St#1]
I run setup-makefile.sh.
It give me so much errors
39St-vendor-blobs.mk: No such file or directory
./setup-makefiles.sh: line 122: ../../../vendor/ZTE/N939St/N939St-vendor.mk: No such file or directory
./setup-makefiles.sh: line 140: ../../../vendor/ZTE/N939St/BoardConfigVendor.mk: No such file or directory
./setup-makefiles.sh: line 288: ../../../vendor/ZTE/N939St/Android.mk: No such file or directory

**Comment by Panyoujies** [comment]
Why do you run this?

**Comment by comword** [comment]
I need this kernel to compile a driver for my phone, could you please tell me how to do?

**Comment by comword** [comment]
make[1]: *** /home/panyoujie/cm12.1/kernel/zte/N939St: No su
ch file or directory.  Stop.
I already set environment varible ARCH=arm64

**Comment by comword** [comment]
Your QQ, need a authentication, a phone number, I really need your help, thx.

**Comment by Panyoujies** [comment]
qq:1724962375

**Comment by comword** [comment]
验证问题:我的电话号码？
要不你加我吧，854676575
